# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af5bbf8a6f713cc3202e16c7c734d64bbfad6fc50c7a74e5fbd34769c9989ccc79361d7ad3ddb47471fb9f6877eb344bde9e77160cc49611d102d3d500bd63fb

test:
  secret_key_base: 1ccedda8cd18325cb96ab594b7af20073ced8e91f250b35e15c86592b35d576651ecf31b06e16b7ddb5ad88c09375c1c1db84215cffcb7d1b4f138a00a8a6ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
